version: "3"

tasks:
  uv:
    cmds:
      - uv {{.CLI_ARGS}}

  coverage:
    cmds:
      - coverage run --source=tailwind_processor -m unittest discover
      - coverage report --omit 'test/*'
      - coverage html


